restaurant/urls.py
from django.urls import path
from restaurant import views


app_name = "restaurant"

urlpatterns = [
    path("", views.index, name="index"),
    path("dish_types/", views.DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_types/<int:pk>/", views.DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dish_types/create/", views.DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_types/update/<int:pk>/", views.DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish_types/delete/<int:pk>/", views.DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dishes/", views.DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", views.DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dishes/update/<int:pk>/", views.DishUpdateView.as_view(), name="dish-update"),
    path("dishes/delete/<int:pk>/", views.DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", views.CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", views.CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", views.CookCreateView.as_view(), name="cook-create"),
    path("cooks/update/<int:pk>/", views.CookUpdateView.as_view(), name="cook-update"),
    path("cooks/dalete/<int:pk>/", views.CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/toggle_assign/<int:pk>/", views.toggle_assign_to_dish, name="toggle-dish-assign"),

]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
<ul class="pagination pagination-lg justify-content-center pb-3 mt-5">
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a href="?{% query_transform request page=1 %}" class="page-link shadow-lg">&laquo; first</a>
  </li>
  <li class="page-item">
    <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link shadow-lg">prev</a>
  </li>
  {% else %}
  <li class="page-item"><a class="page-link shadow-lg cursor-pointer">&laquo; first</a></li>
  <li class="page-item"><a class="page-link shadow-lg cursor-pointer">prev</a></li>
  {% endif %}

  <li class="page-item active">
    <a class="page-link shadow-lg bg-gradient-primary cursor-pointer">
      {{ page_obj.number }} of {{ paginator.num_pages }}</a>
  </li>

  {% if page_obj.has_next %}
  <li class="page-item">
    <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link shadow-lg">next</a>
  </li>
  <li class="page-item">
    <a href="?{% query_transform request page=page_obj.paginator.num_pages %}" class="page-link shadow-lg">last
      &raquo;</a>
  </li>
  {% else %}
  <li class="page-item"><a class="page-link shadow-lg cursor-pointer">next</a></li>
  <li class="page-item"><a class="page-link shadow-lg cursor-pointer">last &raquo;</a></li>
  {% endif %}

</ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}

<form method="get" action="" class="input-group">
  {{ search_form|crispy }}
  <input type="submit" value="🔎" class="btn btn-secondary">
</form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
  <li class="list-group-item">User: <a href="#">{{ user.username }}</a></li>
  <li class="list-group-item"><a href="{% url 'logout'%}">Logout</a></li>
  {% else %}
  <li class="list-group-item"><a href="{% url 'login'%}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'restaurant:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:cook-list' %}">All cooks</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dish-type-list' %}">All dish types</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dish-list' %}">All dishes</a></li>
</ul>