restaurant/urls.py
from django.urls import path
from restaurant import views


app_name = "restaurant"

urlpatterns = [
    path("", views.index, name="index"),
    path("dish_types/", views.DishTypeListView.as_view(), name="dish-type-list"),
    path("dish_types/<int:pk>/", views.DishTypeDetailView.as_view(), name="dish-type-detail"),
    path("dish_types/create/", views.DishTypeCreateView.as_view(), name="dish-type-create"),
    path("dish_types/update/<int:pk>/", views.DishTypeUpdateView.as_view(), name="dish-type-update"),
    path("dish_types/delete/<int:pk>/", views.DishTypeDeleteView.as_view(), name="dish-type-delete"),
    path("dishes/", views.DishListView.as_view(), name="dish-list"),
    path("dishes/<int:pk>/", views.DishDetailView.as_view(), name="dish-detail"),
    path("dishes/create/", views.DishCreateView.as_view(), name="dish-create"),
    path("dishes/update/<int:pk>/", views.DishUpdateView.as_view(), name="dish-update"),
    path("dishes/delete/<int:pk>/", views.DishDeleteView.as_view(), name="dish-delete"),
    path("cooks/", views.CookListView.as_view(), name="cook-list"),
    path("cooks/<int:pk>/", views.CookDetailView.as_view(), name="cook-detail"),
    path("cooks/create/", views.CookCreateView.as_view(), name="cook-create"),
    path("cooks/update/<int:pk>/", views.CookUpdateView.as_view(), name="cook-update"),
    path("cooks/dalete/<int:pk>/", views.CookDeleteView.as_view(), name="cook-delete"),
    path("dishes/toggle_assign/<int:pk>/", views.toggle_assign_to_dish, name="toggle-dish-assign"),

]

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

restaurant/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:dish-type-detail", args=[self.pk])


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    class Meta:
        verbose_name_plural = "dishes"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:dish-detail", args=[self.pk])


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"
        ordering = ["username"]

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", args=[self.pk])

restaurant/forms.py
import re


from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


from restaurant.models import Dish, Cook, DishType


def validate_first_letter_uppercase(value):
    if not value[0].isupper():
        raise ValidationError(
            "Ensure that the first letter of this value is uppercase."
        )


def validate_letters_only(value):
    pattern = r"^[a-zA-Z\s]+$"
    if not re.match(pattern, value):
        raise ValidationError("The value must contain only letters.")


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=150,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class DishForm(forms.ModelForm):
    name = forms.CharField(
        min_length=3,
        validators=[
            validate_first_letter_uppercase,
            validate_letters_only
        ],
        widget=forms.TextInput(attrs={"placeholder": "Enter dish name"}),
    )
    description = forms.CharField(
        min_length=3,
        validators=[validate_first_letter_uppercase],
        widget=forms.Textarea(attrs={
            "rows": 4,
            "placeholder": "Write a short description for the dish"
        }),
    )
    price = forms.DecimalField(
        min_value=0.01,
        max_value=9999.99,
        help_text="Enter a price from 0.01 to 9999.99"
    )
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeForm(forms.ModelForm):
    name = forms.CharField(
        min_length=3,
        validators=[
            validate_first_letter_uppercase,
            validate_letters_only
        ],
        widget=forms.TextInput(attrs={"placeholder": "Enter dish type here"}),
    )

    class Meta:
        model = DishType
        fields = "__all__"


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook

restaurant/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse_lazy

from restaurant.models import Dish, DishType, Cook
from restaurant.forms import (
    DishForm,
    CookCreationForm,
    CookSearchForm,
    DishSearchForm,
    DishTypeSearchForm,
)


@login_required
def index(request: HttpRequest) -> HttpResponse:

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits,
    }

    return render(request, "restaurant/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "restaurant/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all().order_by("name")
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class DishTypeDetailView(LoginRequiredMixin, generic.DetailView):
    model = DishType
    template_name = "restaurant/dish_type_detail.html"
    context_object_name = "dish_type"


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    template_name = "restaurant/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    context_object_name = "dish_type"
    template_name = "restaurant/dish_type_confirm_delete.html"
    success_url = reverse_lazy("restaurant:dish-type-list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(initial={"name": name})
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type").order_by("price")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = CookSearchForm(initial={"username": username})
        return context

    def get_queryset(self):
        queryset = Cook.objects.all()
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(username__icontains=form.cleaned_data["username"])
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = (
        "username",
        "first_name",
        "last_name",
        "email",
        "years_of_experience"
    )


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cook-list")

@login_required
def toggle_assign_to_dish(request, pk):
    dish = get_object_or_404(Dish, id=pk)
    user = request.user
    if user in dish.cooks.all():
        dish.cooks.remove(user)
    else:
        dish.cooks.add(user)
    return HttpResponseRedirect(reverse_lazy(
        "restaurant:dish-detail", args=[pk])
    )

templates/restaurant/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  {% block title %}
  <title>Restaurant kitchen service</title>
  {% endblock %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"/>
  <link rel="icon" href="https://www.svgrepo.com/show/429377/bibimbub-cooking-food.svg">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
{% block navbar %}
{% endblock %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      {% block sidebar %}
      {% include 'includes/sidebar.html' %}
      {% endblock %}
    </div>
    <div class="col-sm-10">
      {% block content %}

      {% endblock %}
      {% block pagination %}
      {% include 'includes/pagination.html' %}
      {% endblock %}
    </div>
  </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
<footer></footer>
</html>

templates/restaurant/cook_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>Delete {{ cook.username }}?</h1>
<form action="" method="post">
  {% csrf_token %}

  <input type="submit" value="Yes" class="btn btn-danger btn-md"/>
  <a href="{% url 'restaurant:cook-detail' cook.id %}" class="btn btn-success btn-md">Cansel</a>
</form>
{% endblock %}

templates/restaurant/cook_detail.html
{% extends 'base.html' %}

{% block content %}
<h2 class="make-dish">username: {{ cook.username }}</h2>
<div class="border-radius-xl blur-section px-4 pt-3 pb-1 my-3">
  <p class="text-dark">
    <strong>Email address:</strong> {{ cook.email }}
  </p>
  <p class="text-dark">
    <strong>First name:</strong> {{ cook.first_name }}
  </p>
  <p class="text-dark">
    <strong>Last name:</strong> {{ cook.last_name }}
  </p>
  <p class="text-dark">
    <strong>Years of experience:</strong> {{ cook.years_of_experience }}
  </p>
</div>

<div class="border-radius-xl blur-section px-4 pt-3 pb-1">
  <h4>Dishes that the cook prepares</h4>
  <ul>
    {% for dish in cook.dishes.all %}
    <li>
      <a class="text-gradient text-primary" href="{% url 'restaurant:dish-detail' dish.id %}">{{ dish.name }}</a>
    </li>
    {% empty %}
    <li>There are no dishes here.</li>
    {% endfor %}
  </ul>
</div><br/>
<div class="make-dish">
  <a href="{% url 'restaurant:cook-update' cook.id %}" class="btn btn-primary btn-lg">Update profile</a><br/><br/>
  <a href="{% url 'restaurant:cook-delete' cook.id %}" class="btn btn-danger btn-lg">Delete account</a>
</div>
{% endblock %}

templates/restaurant/cook_form.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_filters %}

<h1>{{ object|yesno:"Update, Create" }} Cook</h1>

<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form | crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
</form>
{% endblock %}

templates/restaurant/cook_list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="make-dish">Cook list</h1>
{% include 'includes/search_form.html' %}
{% if cook_list %}
<table class="table table-bordered table-hover shadow-lg bg-white mt-5">
  <thead>
  <tr>
    <th>ID</th>
    <th>Full name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Work experience</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for cook in cook_list %}
  <tr>
    <td>{{ cook.id }}</td>
    <td>
      <a href="{{ cook.get_absolute_url }}">
        {{ cook.first_name }} {{ cook.last_name }}
      </a>
    </td>
    <td>{{ cook.username}}</td>
    <td>{{ cook.email }}</td>
    <td>{{ cook.years_of_experience }}</td>
    <td>
      <a href="{% url 'restaurant:cook-update' cook.id %}">Update</a>
    </td>
    <td>
      <a href="{% url 'restaurant:cook-delete' cook.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no cooks</p>
{% endif %}
<div class="make-dish">
  <p><b>Create a new profile</b></p>
  <a href="{% url 'restaurant:cook-create' %}" class="btn btn-success btn-lg">Create</a><br/>
</div>
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="make-dish mt-5">
  <h1>Delete {{ dish.name }}?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger btn-md"/>
    <a href="{% url 'restaurant:dish-detail' dish.id %}" class="btn btn-success">Cansel</a>
  </form>
</div>
{% endblock %}

templates/restaurant/dish_detail.html
{% extends 'base.html' %}
{% block content %}
{% load price_formatters %}
<div class="make-dish mt-5">
  <h5><span class="more-space">
      <strong> Dish:</strong>
      {{ dish.name }}
    </span>
    <span>
        {% if dish in user.dishes.all %}
          <a href="{% url 'restaurant:toggle-dish-assign' dish.id %}"
             class="btn btn-danger">Delete me from this dish</a>
        {% else %}
          <a href="{% url 'restaurant:toggle-dish-assign' dish.id %}" class="btn btn-success">Assign me to this dish</a>
        {% endif %}
      </span>
  </h5>
  <h5>Dish type:</h5>
  <h6>
    <a href="{% url 'restaurant:dish-type-detail' dish.dish_type.id %}">{{ dish.dish_type }}</a>
  </h6>
  <h5>Price: {{ dish.price | currency_euro }}</h5>
  <h5>Description</h5>
  <div class="contain-text">
    <p>{{ dish.description }}</p>

  </div>
  <h5>
    <span>Cooks preparing this dish</span>
  </h5>

  {% for cook in dish.cooks.all %}
  <h5><a href="{% url 'restaurant:cook-detail' cook.id %}">{{ cook.username }}</a></h5>
  {% empty %}
  <h5>There are no cooks</h5>

  {% endfor %}

  <br>
  <a href="{% url 'restaurant:dish-update' dish.id %}" class="btn btn-primary">Update</a>
  <a href="{% url 'restaurant:dish-delete' dish.id %}" class="btn btn-danger">Delete</a>
</div>

{% endblock %}

templates/restaurant/dish_form.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_filters %}
<h2>{{ object|yesno:'Update, Create' }} Dish</h2>
<form action="" method="post" novalidate>
  {% csrf_token %}
  {{ form|crispy }}
  <br/>
  <input class="btn btn-primary" type="submit" value="Submit"/>
</form>
{% endblock %}

templates/restaurant/dish_list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="make-dish">All dishes</h1>
{% include 'includes/search_form.html' %}
{% load price_formatters %}
{% if dish_list %}
<table class="table table-bordered table-hover shadow-lg bg-white mt-5">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Price</th>
    <th>Dish Type</th>
    <th>Cook</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for dish in dish_list %}
  <tr>
    <td>{{ dish.id }}</td>
    <td>
      <a href="{{ dish.get_absolute_url }}">
        {{ dish.name }}
      </a>
    </td>
    <td>{{ dish.price|currency_euro }}</td>
    <td>{{ dish.dish_type.name}}</td>
    <td>
      {% for cook in dish.cooks.all %}
      {% if cook.first_name %}
      {{ cook.first_name }} {{ cook.last_name }}
      <br/>
      {% else %}
      {{ cook.username }}
      {% endif %}
      {% endfor %}
    </td>
    <td>
      <a href="{% url 'restaurant:dish-update' dish.id %}">Update</a>
    </td>
     <td>
      <a href="{% url 'restaurant:dish-delete' dish.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no dishes</p>
{% endif %}
<div class="make-dish">
  <p>Create a new dish</p>
  <a href="{% url 'restaurant:dish-create' %}" class="btn btn-success btn-lg">Create</a>
</div>
{% endblock %}

templates/restaurant/dish_type_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<h2>Delete {{ dish_type.name }}?</h2>
<form action="" method="post">
  {% csrf_token %}

  <input type="submit" value="Yes" class="btn btn-danger btn-md"/>
  <a href="{% url 'restaurant:dish-type-list' %}" class="btn btn-success">Cansel</a>
</form>
{% endblock %}

templates/restaurant/dish_type_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="make-dish mt-5">
  <h5>Dish type: {{ dish_type.name }}</h5><br>
  <h5>This dish type consists of such dishes:</h5>
  {% for dish in dish_type.dish_set.all %}
  <h5><a href="{{ dish.get_absolute_url }}">
    {{ dish.name }}
  </a>
  </h5><br>
  {% empty %}
  <h5>There are no dishes</h5><br>
  {% endfor %}
  <a href="{% url 'restaurant:dish-type-update' dish_type.id %}" class="btn btn-primary">Update</a>
  <a href="{% url 'restaurant:dish-type-delete' dish_type.id %}" class="btn btn-danger">Delete</a>
</div>
{% endblock %}

templates/restaurant/dish_type_form.html
{% extends 'base.html' %}
{% block content %}
  {% load crispy_forms_filters %}
  <h2>{{ object|yesno:'Update, Create' }} Dish Type</h2>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form | crispy }}
    <br>
    <input class="btn btn-primary" type="submit" value="Submit" />
  </form>
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends 'base.html' %}

{% block content %}
<h1 class="make-dish">All Dish Types</h1>
{% include 'includes/search_form.html' %}
{% if dish_type_list %}
<table class="table table-bordered table-hover shadow-lg bg-white mt-5">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  </thead>
  <tbody>
  {% for dish_type in dish_type_list %}
  <tr>
    <td>{{ dish_type.id }}</td>
    <td>
      <a href="{{ dish_type.get_absolute_url }}">
        {{ dish_type.name }}
      </a>
    </td>
    <td>
      <a href="{% url 'restaurant:dish-type-update' dish_type.id %}">Update</a>
    </td>
    <td>
      <a href="{% url 'restaurant:dish-type-delete' dish_type.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no dish types</p>
{% endif %}
<div class="make-dish">
  <p>
    <strong>Create a new dish type</strong>
  </p>
  <a href="{% url 'restaurant:dish-type-create' %}" class="btn btn-success btn-lg"><b>Create</b></a>
</div>
{% endblock %}

templates/restaurant/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Restaurant Kitchen Service Home</h1>
  <p>Welcome to Best Restaurant Ever!</p>

  <h2>Dynamic content</h2>
  <p>The restaurant kitchen service has the following record counts:</p>

  <ul>
    <li><strong>Cooks:</strong> {{ num_cooks }}</li>
    <li><strong>Dish Types:</strong> {{ num_dish_types }}</li>
    <li><strong>Dishes:</strong> {{ num_dishes }}</li>
  </ul>

  <p>You have visited this page
      {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>
{% endblock %}